import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from "@/components/menu/menu";

const maragsaSans = localFont({
  src: "./fonts/Maragsâ-Display.otf",
  variable: "--font-marag-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${maragsaSans} antialiased`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
